# Generated by Django 4.2.3 on 2023-07-22 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musker', '0004_mepp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mepp',
            new_name='Meep',
        ),
    ]
